Внесение имя наставника
htmlacademy-javascript/2044521-keksobooking-25 pull request #3
Opened 2022-02-21 20:55 UTC by Lokfort

2022-02-22 06:35 UTC, babtshe requested changes

2022-02-22 06:35 UTC, babtshe commented on Readme.md
> +* Наставник: `Aleksander Babchenko`.
Хорошо бы ещё ссылку на профиль добавить как на строке выше.

2022-02-22 12:37 UTC, Lokfort commented on Readme.md
> +* Наставник: `Aleksander Babchenko`.
Сделано!

2022-02-22 12:57 UTC, babtshe requested changes

2022-02-22 12:57 UTC, babtshe commented on Readme.md
> +* Наставник: <a href = "https://github.com/babtshe">`Aleksander Babchenko`</a>.
в это случае readme будет выглядеть как-то так:
![image](https://user-images.githubusercontent.com/30229773/155136729-3bc6c60a-b67d-4287-9425-6963504a4086.png)
Уже неплохо, но можно лучше. Можно посмотреть доку по формату `markdown` либо создать ссылку по аналогии с 3 строкой.

2022-02-22 13:46 UTC, Lokfort commented on Readme.md
> +* Наставник: <a href = "https://github.com/babtshe">`Aleksander Babchenko`</a>.
Сделано!

2022-02-23 07:52 UTC, babtshe approved these changes

2022-02-23 07:52 UTC, merged